server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mongodb
    source: mongodb://localhost:27017/?maxPoolSize=20&w=majority
    db: bee
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
config:
  server:
    baseUrl: "/api/v1"
    access: restricted
    logger:
      level: "info"
      format: "json"
