// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bee

import (
	"context"
	documents2 "github.com/luminosita/docrepo-bee/internal/app/use-cases/documents"
	"github.com/luminosita/docrepo-bee/internal/infra/db/mongodb/repositories"
	"github.com/luminosita/docrepo-bee/internal/infra/grpc/handlers"
	"github.com/luminosita/docrepo-bee/internal/infra/http/handlers/documents"
)

// Injectors from wire.go:

func MakeGetDocumentHandler(ctx context.Context) *documents.GetDocumentHandler {
	getDocumentRepository := repositories.NewGetDocumentRepository(ctx)
	getDocument := documents2.NewGetDocument(getDocumentRepository)
	getDocumentHandler := documents.NewGetDocumentHandler(getDocument)
	return getDocumentHandler
}

func MakeGetDocumentInfoHandler(ctx context.Context) *documents.GetDocumentInfoHandler {
	getDocumentInfoRepository := repositories.NewGetDocumentInfoRepository(ctx)
	getDocumentInfo := documents2.NewGetDocumentInfo(getDocumentInfoRepository)
	getDocumentInfoHandler := documents.NewGetDocumentInfoHandler(getDocumentInfo)
	return getDocumentInfoHandler
}

func MakePutDocumentHandler(ctx context.Context) *documents.PutDocumentHandler {
	putDocumentRepository := repositories.NewPutDocumentRepository(ctx)
	putDocument := documents2.NewPutDocument(putDocumentRepository)
	putDocumentHandler := documents.NewPutDocumentHandler(putDocument)
	return putDocumentHandler
}

func MakeGrpcDocumentServer(ctx context.Context) *handlers.DocumentsServer {
	getDocumentInfoRepository := repositories.NewGetDocumentInfoRepository(ctx)
	getDocumentInfo := documents2.NewGetDocumentInfo(getDocumentInfoRepository)
	getDocumentRepository := repositories.NewGetDocumentRepository(ctx)
	getDocument := documents2.NewGetDocument(getDocumentRepository)
	putDocumentRepository := repositories.NewPutDocumentRepository(ctx)
	putDocument := documents2.NewPutDocument(putDocumentRepository)
	documentsServer := handlers.NewDocumentsServer(getDocumentInfo, getDocument, putDocument)
	return documentsServer
}
